const REACTIONS = [
  // 一、与单质反应
  {
    id: 'r01',
    name: '铝与氢氧化钠',
    equation: '2Al + 2NaOH + 2H₂O → 2NaAlO₂ + 3H₂↑',
    latex: '\\ce{2Al + 2NaOH + 2H_{2}O = 2NaAlO_{2} + 3H_{2}↑}',
    category: '单质反应',
    section: '一、与单质反应',
    note: '重点反应，Al的两性体现',
  },
  {
    id: 'r02',
    name: '硅与氢氧化钠',
    equation: 'Si + 2NaOH + H₂O → Na₂SiO₃ + 2H₂↑',
    latex: '\\ce{Si + 2NaOH + H_{2}O = Na_{2}SiO_{3} + 2H_{2}↑}',
    category: '单质反应',
    section: '一、与单质反应',
    note: 'Si的歧化反应',
  },
  {
    id: 'r03',
    name: '氯气与氢氧化钠（常温）',
    equation: 'Cl₂ + 2NaOH → NaCl + NaClO + H₂O',
    latex: '\\ce{Cl_{2} + 2NaOH = NaCl + NaClO + H_{2}O}',
    category: '单质反应',
    section: '一、与单质反应',
    note: '歧化反应，常温产物为次氯酸盐',
  },
  {
    id: 'r04',
    name: '氯气与氢氧化钠（加热）',
    equation: '3Cl₂ + 6NaOH → 5NaCl + NaClO₃ + 3H₂O',
    latex: '\\ce{3Cl_{2} + 6NaOH \\xlongequal{\\Delta} 5NaCl + NaClO_{3} + 3H_{2}O}',
    category: '单质反应',
    section: '一、与单质反应',
    note: '加热歧化，生成氯酸盐',
  },
  {
    id: 'r05',
    name: '硫与氢氧化钠',
    equation: '3S + 6NaOH → 2Na₂S + Na₂SO₃ + 3H₂O',
    latex: '\\ce{3S + 6NaOH \\xlongequal{\\Delta} 2Na_{2}S + Na_{2}SO_{3} + 3H_{2}O}',
    category: '单质反应',
    section: '一、与单质反应',
    note: '硫的歧化反应',
  },

  // 二、与酸性氧化物反应
  {
    id: 'r06',
    name: 'CO₂过量 → 碳酸氢钠',
    equation: 'NaOH + CO₂ → NaHCO₃',
    latex: '\\ce{NaOH + CO_{2} = NaHCO_{3}}',
    category: '酸性氧化物',
    section: '二、与酸性氧化物反应',
    note: 'CO₂过量，生成酸式盐，大题高频',
  },
  {
    id: 'r07',
    name: 'NaOH过量 → 碳酸钠',
    equation: '2NaOH + CO₂ → Na₂CO₃ + H₂O',
    latex: '\\ce{2NaOH + CO_{2} = Na_{2}CO_{3} + H_{2}O}',
    category: '酸性氧化物',
    section: '二、与酸性氧化物反应',
    note: 'NaOH过量，生成正盐',
  },
  {
    id: 'r08',
    name: 'SO₂与氢氧化钠',
    equation: '2NaOH + SO₂ → Na₂SO₃ + H₂O',
    latex: '\\ce{2NaOH + SO_{2} = Na_{2}SO_{3} + H_{2}O}',
    category: '酸性氧化物',
    section: '二、与酸性氧化物反应',
    note: 'SO₂过量生成NaHSO₃',
  },
  {
    id: 'r09',
    name: 'SiO₂与氢氧化钠',
    equation: '2NaOH + SiO₂ → Na₂SiO₃ + H₂O',
    latex: '\\ce{2NaOH + SiO_{2} = Na_{2}SiO_{3} + H_{2}O}',
    category: '酸性氧化物',
    section: '二、与酸性氧化物反应',
    note: '玻璃不能用磨口玻璃塞的原因',
  },

  // 三、与酸反应
  {
    id: 'r10',
    name: '普通强酸中和',
    equation: 'NaOH + HCl → NaCl + H₂O',
    latex: '\\ce{NaOH + HCl = NaCl + H_{2}O}',
    category: '酸碱中和',
    section: '三、与酸反应（中和）',
    note: '强酸强碱中和',
  },
  {
    id: 'r11',
    name: '弱酸中和',
    equation: 'NaOH + CH₃COOH → CH₃COONa + H₂O',
    latex: '\\ce{NaOH + CH_{3}COOH = CH_{3}COONa + H_{2}O}',
    category: '酸碱中和',
    section: '三、与酸反应（中和）',
    note: '弱酸也反应',
  },
  {
    id: 'r12',
    name: '多元酸（H₂S）',
    equation: '2NaOH + H₂S → Na₂S + 2H₂O',
    latex: '\\ce{2NaOH + H_{2}S = Na_{2}S + 2H_{2}O}',
    category: '酸碱中和',
    section: '三、与酸反应（中和）',
    note: '多元酸可分步反应',
  },

  // 四、两性
  {
    id: 'r13',
    name: '氧化铝与氢氧化钠',
    equation: 'Al₂O₃ + 2NaOH → 2NaAlO₂ + H₂O',
    latex: '\\ce{Al_{2}O_{3} + 2NaOH = 2NaAlO_{2} + H_{2}O}',
    category: '两性',
    section: '四、与两性氢氧化物/氧化物',
    note: 'Al₂O₃的两性',
  },
  {
    id: 'r14',
    name: '氢氧化铝与氢氧化钠',
    equation: 'Al(OH)₃ + NaOH → NaAlO₂ + 2H₂O',
    latex: '\\ce{Al(OH)_{3} + NaOH = NaAlO_{2} + 2H_{2}O}',
    category: '两性',
    section: '四、与两性氢氧化物/氧化物',
    note: 'Al(OH)₃的两性，高考必考',
  },

  // 五、与盐反应
  {
    id: 'r15',
    name: '铵盐制氨气',
    equation: 'NH₄Cl + NaOH → NaCl + NH₃↑ + H₂O',
    latex: '\\ce{NH_{4}Cl + NaOH \\xlongequal{\\Delta} NaCl + NH_{3}↑ + H_{2}O}',
    category: '复分解',
    section: '五、与盐反应（复分解/水解）',
    note: '实验室制氨气，必考',
  },
  {
    id: 'r16',
    name: '硫酸铜沉淀',
    equation: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄',
    latex: '\\ce{CuSO_{4} + 2NaOH = Cu(OH)_{2}↓ + Na_{2}SO_{4}}',
    category: '复分解',
    section: '五、与盐反应（复分解/水解）',
    note: '典型沉淀反应',
  },
  {
    id: 'r17',
    name: '氯化铁沉淀',
    equation: 'FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl',
    latex: '\\ce{FeCl_{3} + 3NaOH = Fe(OH)_{3}↓ + 3NaCl}',
    category: '复分解',
    section: '五、与盐反应（复分解/水解）',
    note: '棕褐色沉淀',
  },
  {
    id: 'r18',
    name: '碳酸氢钠与氢氧化钠',
    equation: 'NaHCO₃ + NaOH → Na₂CO₃ + H₂O',
    latex: '\\ce{NaHCO_{3} + NaOH = Na_{2}CO_{3} + H_{2}O}',
    category: '复分解',
    section: '五、与盐反应（复分解/水解）',
    note: '酸式盐与碱反应',
  },

  // 六、有机反应
  {
    id: 'r19',
    name: '卤代烃水解（取代）',
    equation: 'CH₃CH₂Br + NaOH → CH₃CH₂OH + NaBr',
    latex: 'CH3CH2Br + NaOH → CH3CH2OH + NaBr (H2O, 取代)',
    category: '有机反应',
    section: '六、有机反应',
    note: '水溶液，取代反应',
  },
  {
    id: 'r20',
    name: '卤代烃消去',
    equation: 'CH₃CH₂Br + NaOH → CH₂=CH₂↑ + NaBr + H₂O',
    latex: 'CH3CH2Br + NaOH → CH2=CH2 + NaBr + H2O (醇, 加热, 消去)',
    category: '有机反应',
    section: '六、有机反应',
    note: '醇溶液，消去反应',
  },
  {
    id: 'r21',
    name: '油脂皂化反应',
    equation: '油脂 + NaOH → 高级脂肪酸钠 + 甘油',
    latex: '高级脂肪酸甘油酯 + \\ce{NaOH} → 高级脂肪酸钠 + 甘油',
    category: '有机反应',
    section: '六、有机反应',
    note: '碱性水解，制肥皂',
  },
  {
    id: 'r22',
    name: '苯酚与氢氧化钠',
    equation: 'C₆H₅OH + NaOH → C₆H₅ONa + H₂O',
    latex: '\\ce{C_{6}H_{5}OH + NaOH → C_{6}H_{5}ONa + H_{2}O}',
    category: '有机反应',
    section: '六、有机反应',
    note: '酚羟基显弱酸性',
  },
  {
    id: 'r23',
    name: '酯的碱性水解（皂化）',
    equation: 'RCOOR\' + NaOH → RCOONa + R\'OH',
    latex: 'RCOOR + NaOH = RCOONa + ROH',
    category: '有机反应',
    section: '七、酯的碱性水解',
    note: '酯在碱性条件下彻底水解',
  },
];

const CATEGORIES = ['全部', '单质反应', '酸性氧化物', '酸碱中和', '两性', '复分解', '有机反应'];

export { REACTIONS, CATEGORIES };
